### ISSUE TITLE
Sloth emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#112]
The Sloth is a symbol for lazyness or relaxing, and has a characteristic look to it – often shown upside down.

## Petitions

- [change.org: Sloth](https://www.change.org/p/apple-verizon-sprint-apple-should-make-a-sloth-emoji)
- [change.org: Sloth](https://www.change.org/p/steve-jobs-apple-apple-inc-make-a-sloth-emoji-for-the-ios-devices)
- [change.org: Sloth (and Pug)](https://www.change.org/p/everyone-make-a-sloth-and-pug-emoji)

**Comment by Crissov** [comment]
- https://www.change.org/p/apple-sloth-emoji-f02993b7-7f55-4a1b-8902-173dcb92bf10

**Comment by bitboxer** [comment]
I started to work on this 😉 

https://media.giphy.com/media/kfZGiucm1aVJS/giphy.gif

**Comment by spixi** [comment]
The Sloth Emoji has been proposed by Bodo Tasche, Kelly Blanchat and Jennifer 8. Lee.

http://www.unicode.org/L2/L2018/18074-sloth-emoji-.pdf

**Comment by Crissov** [comment]
[Sloth](https://emojipedia.org/sloth/) is a Candidate for Emoji 12.0 (2019).
