### ISSUE TITLE
❤️‍☀️‍💚 Kurdish Flag emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#117]
Kurdistan is the region in South-West Asia historically inhabited by the Kurds. It hasn’t been an independent country lately and is divided across several states: Turkey, Iran, Iraq, Syria. No ISO 3166-2 subdivision matches a collective Kurdish region, although they enjoy some autonomy in Iraq now. ISO 3166-2:IQ still only has code elements for governates, not regions, though. Kurdistan does have a top-level domain, `.krd`, but it’s not really a geographical ccTLD.

It would perhaps be the simplest solution to have the Kurdish administration ask the ISO 3166 Maintenance Agency to add codes for Iraqi regions, e.g. `IQ-K` or `IQ-KRD` – vendors could use the respective Emoji Tag Sequence described in UTR#51 then. For reference, ISO 3166-2:GB encodes at least 3 different levels (and many more kinds) of subdivisions of the United Kingdom of Great Britain and Northern Ireland, whereas most other national parts only use one level of codes.

The design of the [Kurdish Flag](https://en.wikipedia.org/wiki/Flag_of_Kurdistan) is like the Hungarian flag 🇭🇺, i.e. three horizontal stripes (red, white and green), with a yellow sun ☀️/🌞 added in the center. Interested people *could* agree to adopt a canonical sequence like ❤️‍☀️‍💚 for now. (There is no White Heart emoji. #222)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_Kurdistan.svg/255px-Flag_of_Kurdistan.svg.png)

In theory, Syrian Kurds could do the same for the Rojava region, but it is not a formal political entity (yet), and the defacto/informal authorities are using a different flag design, i.e. yellow, red and green horizontal bars 💛❤️💚. Since the Turkish administration actively opposes Kurdish autonomy, it would be more difficult to get an appropriate code there. I’m not sure at all about the situation in Iran.

The original standard UN M.49 uses 3-digit numeric codes and also encodes macro regions like whole continents or groups of neighboring countries with similar development index. They could, in theory, add an individual code for the whole of Kurdistan (however determined). This would not be completely without precedent, as they used to have codes for independence movements, especially in post-colonial Africa, but it’s highly unlikjely to happen. Also, numeric codes are not (yet) supported by UTR#51, although it would be a straight-forward extension, cf. #203. 

The geographical flag should not be confused with political ones like the one of the PKK:

![Kurdish Workers Party flag](https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Flag_of_Kurdistan_Workers%27_Party.svg/162px-Flag_of_Kurdistan_Workers%27_Party.svg.png)

## Petitions

- [The Petition Site](http://www.thepetitionsite.com/689/689/556/kurdish-flag-emoji/)

## Standards

- [UTR#51.10+](http://www.unicode.org/reports/tr51/proposed.html#valid-emoji-tag-sequences)
- [ISO 3166-2:IQ](https://www.iso.org/obp/ui/#iso:code:3166:IQ) – Iraq ([at Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-2:IQ)): `IQ-AR`, `IQ-SU`, `IQ-DA`
- [ISO 3166-2:IR](https://www.iso.org/obp/ui/#iso:code:3166:IR) – Iran ([at Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-2:IR)): `IR-16` …
- [ISO 3166-2:SY](https://www.iso.org/obp/ui/#iso:code:3166:SY) – Syria ([at Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-2:SY)): `SY-HA`, `SY-HL`
- [ISO 3166-2:TR](https://www.iso.org/obp/ui/#iso:code:3166:TR) – Turkey ([at Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-2:TR)): …

**Comment by Crissov** [comment]
Today I’ve [informally asked](https://twitter.com/Informoji/status/832542477286531072) [@KurdistanRegion on Twitter](https://twitter.com/KurdistanRegion) to propose to [ISO 3166/MA](http://www.iso.org/iso/home/standards_development/list_of_iso_technical_committees/maintenance_agencies.htm#3166) [`customerservice@iso.org`](http://www.iso.org/iso/country_codes.htm) that a new code element be added to ISO 3166-2:IQ.

**Comment by Crissov** [comment]
Mockups
----------

Twemoji: ![Sun with Face,](https://cloud.githubusercontent.com/assets/6200185/24823996/02df11b2-1c05-11e7-900d-f234b38b14f9.png) ![Sun with Rays](https://cloud.githubusercontent.com/assets/6200185/24823997/02df0988-1c05-11e7-8215-f8ae95694578.png)

**Comment by spacekitteh** [comment]
Evidence of "Kurdistan" being frequently used:

![kurdistan google trends](https://cloud.githubusercontent.com/assets/1940652/26813183/d05ece78-4abf-11e7-89fc-7b94b4151904.PNG)

**Comment by BarochBamarny** [comment]
![fe15cfe63b79ad72b60a61e1d1d923e4--flag-emoji-kurdistan](https://user-images.githubusercontent.com/30853626/29104810-e6b1483c-7cc8-11e7-8b7c-1a108cf2d1ba.jpg)

**Comment by dizdaizda** [comment]
Thank you very much

**Comment by Rodiloo** [comment]
Do you have any updates?

**Comment by Mennaruuk** [comment]
Yeah, I’d love any updates regarding this. Also, I’d suggest keeping the number of rays at 21, since [it is really important to Kurdish culture](https://en.m.wikipedia.org/wiki/Flag_of_Kurdistan#Symbolism_and_dimensions_of_the_flag).

**Comment by rojserbest** [comment]
> Yeah, I’d love any updates regarding this. Also, I’d suggest keeping the number of rays at 21, since [it is really important to Kurdish culture](https://en.m.wikipedia.org/wiki/Flag_of_Kurdistan#Symbolism_and_dimensions_of_the_flag).

@Mennaruuk this is not a problem because they will be displayed small.

**Comment by Rabar007** [comment]
http://chng.it/dFSqS5gvTj

**Comment by Rabar007** [comment]
http://chng.it/dFSqS5gvTj

**Comment by Crissov** [comment]
- 🔴☀🟢
- 🔴🌞🟢
- 🔴⚪🟢
- 🟥☀🟩
- 🟥🌞🟩
- 🟥⬜🟩

**Comment by rojserbest** [comment]
hmmm

**Comment by a7medpa** [comment]
> http://chng.it/dFSqS5gvTj

People have tried this several times before and it never helps because of the ISO issue with Unicode. 

https://www.change.org/p/united-states-supreme-court-adding-emoji-flag-for-kurdistan

**Comment by SarkarKurdish** [comment]
Hello is there is any update for Kurdish flag? I'm from Kurdistan and I can do anything I can, for making this project work

**Comment by Lindafahmi** [comment]
Linda

**Comment by roj1512** [comment]
> Linda

What?

**Comment by mrvillain374** [comment]
Ey bro I am Kurdish guy has to live in Turkey but in the east side so it is the Kurdish part of the country but man I will do anything I can to help with this project. I think that this going to be a huge step up to stand against the Kurdish haters.

**Comment by Crissov** [comment]
Please note that the current version of the [guidelines](https://www.unicode.org/emoji/proposals.html#Flags) mention the Kurdish flag as an example of something that currently cannot be encoded properly. Therefore, submitting proposals to Unicode is useless at this point. 

> ### F3
>
>	Other regional and geopolitical flags have no mechanism within the Unicode Standard. That is, no mechanism currently exists for regions of the world or geopolitical bodies that do not have a valid Unicode region code (based on ISO/BCP47) or Unicode subdivision code (based on ISO 3166-2).
>
> This includes historical flags (for example: South Vietnam) as well as current flags which do not have a corresponding region code or subdivision code (for example: Assyrian, Australian Aboriginal, Kurdistan, Maori, Torres Strait Islander, NATO).
>
> Until such time as a general mechanism is proposed and accepted, proposals for flags in this category will be not be considered by the Emoji Subcommittee or the UTC.

**Comment by roj1512** [comment]
I don't know why there are flags for some islands that aren't even popular but they have problems with the Kurdish flag.

They, themselves don't know what they should be making or not making flags for.

**Comment by Crissov** [comment]
There is no ISO standard for (codes for) flags, but there is one for geographic regions which was already in use by Unicode CLDR and therefore was chosen a as the base for encoding national flag emojis. There are some codes for subnational entities, mostly remote islands detached from the continent, and some for supranational entities, but those weren't invented by Unicode. The amount of user definable codes therein is quite limited (three dozens or so), but was used by Whatsapp for a handful of flags (of England etc.) for a while; so Unicode added another method to encode sub-regions of the existing codes. This still left out other bodies, unfortunately, and was ill-advised in other ways, too. Nobody really chose not to represent Kurdistan with a flag emoji, it just happens to be a cultural entity not covered by the relevant standards.

**Comment by SarkarKurdish** [comment]
@Crissov Thanks for this nice insight, is there is any thing can be done to make Kurdish flag emoji happen?

**Comment by Crissov** [comment]
No, nothing realistically at this point. 

I'd like to see CLDR use some of the available private-use codes, but since that didn't happen for England, Scotland and Wales at the time (although it did for Kosovo before), this is highly unlikely.

**Comment by broosk1993** [comment]
> Today, I’ve [informally asked](https://twitter.com/Informoji/status/832542477286531072) [@KurdistanRegion on Twitter](https://twitter.com/KurdistanRegion) (i.e. the administration of the Iraqi region) to propose to [ISO 3166/MA](http://www.iso.org/iso/home/standards_development/list_of_iso_technical_committees/maintenance_agencies.htm#3166) [`customerservice@iso.org`](http://www.iso.org/iso/country_codes.htm) that a new code element be added to ISO 3166-2:IQ.
> 
> This is a first step. The second step would be a proposal to Unicode like Jeremy Burge of Emojipedia has (successfully) [done for England, Scotland and Wales](http://blog.emojipedia.org/emoji-flags-approved-for-england-scotland-wales/).

Hello @Crissov,

This is Brusk from @ditkrg (Department of Information Technology, KRG).

What are the formal steps that we need to take in this regard? I appreciate it if you could take me through it as I am very much a novice in this area.

**Comment by broosk1993** [comment]
Dear @Crissov,

Kurdistan Region of Iraq now has an ISO 3166 Code under IQ-KR:

https://www.iso.org/obp/ui/#iso:code:3166:IQ

Kindly, let me know if this is sufficient to move forward.

**Comment by a7medpa** [comment]
> Dear @Crissov,
> 
> Kurdistan Region of Iraq now has an ISO 3166 Code under IQ-KR:
> 
> https://www.iso.org/obp/ui/#iso:code:3166:IQ
> 
> Kindly, let me know if this is sufficient to move forward.

I guess at this point with the information @Crissov has shared then someone can propose it to Unicode (albeit, some of the data needs updating) https://unicode.org/emoji/proposals.html#emoji_proposals_format. Might be worth reading the Flags section too (mentions Kurdistan, although, this may no longer apply with the ISO 3166-2 code for the Kurdistan region).

**Comment by rawandahmad698** [comment]
> > Dear @Crissov,
> 
> > 
> 
> > Kurdistan Region of Iraq now has an ISO 3166 Code under IQ-KR:
> 
> > 
> 
> > https://www.iso.org/obp/ui/#iso:code:3166:IQ
> 
> > 
> 
> > Kindly, let me know if this is sufficient to move forward.
> 
> 
> 
> I guess at this point with the information @Crissov has shared then someone can propose it to Unicode (albeit, some of the data needs updating) https://unicode.org/emoji/proposals.html#emoji_proposals_format. Might be worth reading the Flags section too (mentions Kurdistan, although, this may no longer apply with the ISO 3166-2 code for the Kurdistan region).

"Someone" shouldn't do that, this is a serious matter and only the right people should use it with proper care to avoid abusing/spamming the service, great effort by the KRG government though. This is a 5 year old effort and shall not go to waste.

**Comment by a7medpa** [comment]
> > > Dear @Crissov,
> > 
> > > 
> > 
> > > Kurdistan Region of Iraq now has an ISO 3166 Code under IQ-KR:
> > 
> > > 
> > 
> > > https://www.iso.org/obp/ui/#iso:code:3166:IQ
> > 
> > > 
> > 
> > > Kindly, let me know if this is sufficient to move forward.
> > 
> > 
> > 
> > I guess at this point with the information @Crissov has shared then someone can propose it to Unicode (albeit, some of the data needs updating) https://unicode.org/emoji/proposals.html#emoji_proposals_format. Might be worth reading the Flags section too (mentions Kurdistan, although, this may no longer apply with the ISO 3166-2 code for the Kurdistan region).
> 
> "Someone" shouldn't do that, this is a serious matter and only the right people should use it with proper care to avoid abusing/spamming the service, great effort by the KRG government though. This is a 5 year old effort and shall not go to waste. 

Obviously 'someone' needs to propose it otherwise it will go to waste. 

Of course, the right person should do it and I never condoned anyone to abuse/spam the as you implied.

**Comment by broosk1993** [comment]
We will get the efforts together and work on a proposal. @ditkrg is here to sponsor it and kick start a formal proposal.

If anyone is interested, please hit me up on Twitter: https://twitter.com/bruskawat

**Comment by rawandahmad698** [comment]
> proposal.

The link is dead

**Comment by broosk1993** [comment]
> > proposal.
> 
> The link is dead
> 
> 

Thank you. It's fixed now.

**Comment by 0xdolan** [comment]
Kak @broosk1993, Can we do something to use this ISO for Kurdish Keyboard on Linux or other platforms? And should it be offer formally by KRG (@ditkrg) to be accepted?

**Comment by rantbozan** [comment]
Ez kürdim

**Comment by roj1512** [comment]
@rantbozan ji kerema xwe peyama xwe jê bibe, tu nikarî bi gotina wê li vir ti xizmetekî bikî.

**Comment by rantbozan** [comment]
Heval ez nizanim re nişanbide

15 Mar 2022 Sal 12:41 tarihinde Roj ***@***.***> şunu yazdı:

**Comment by rantbozan** [comment]
Çıma ??

**Comment by rantbozan** [comment]
Çıma ??

15 Mar 2022 Sal 12:46 tarihinde Mesut Sancar ***@***.***>
şunu yazdı:

**Comment by Mennaruuk** [comment]
Bad new for all proposed flags:
https://home.unicode.org/the-past-and-future-of-flag-emoji/

**Comment by roj1512** [comment]
@Mennaruuk It is not a "bad news",

but it simply means that:

- @Crissov should close this issue,
- now we know the fact that the `iqkr` code was released on the May 3rd in last year, and not ~25 days ago,
- everyone should know that no font designer will take the responsibility of supporting "over 5,000
geographically-recognized regions", and
- the tweets made by verified Kurdish people and officials are no longer valid. :)

**Comment by Crissov** [comment]
People can still submit PRs to open-source emoji sets like [Noto Emoji](https://github.com/googlefonts/noto-emoji/tree/main/third_party/region-flags), Openmoji or Emojitwo. (Twemoji doesn’t accept external PRs for graphic changes, only for programming code and metadata changes.) Some projects already have accepted or pending submissions for sub-regional flags that are not RGI, e.g. Canadian, Mexican and US territories in Noto’s third-party folder.

**Comment by roj1512** [comment]
Good news!

**Comment by a7medpa** [comment]
> @Mennaruuk It is not a "bad news",
> 
> 
> 
> but it simply means that:
> 
> 
> 
> - @Crissov should close this issue,
> 
> - now we know the fact that the `iqkr` code was released on the May 3rd in last year, and not ~25 days ago,
> 
> - everyone should know that no font designer will take the responsibility of supporting "over 5,000
> 
> geographically-recognized regions", and
> 
> - the tweets made by verified Kurdish people and officials are no longer valid. :)

Not sure I understand the last point correctly, are you implying that there will be no Kurdish flag emoji?

**Comment by roj1512** [comment]
@a7medpa

> Not sure I understand the last point correctly,

I mean they weren’t right, and "be diro xiranewe".

> are you implying that there will be no Kurdish flag emoji?

Yes.

**Comment by dnkilic** [comment]
As Selahattin Demirtaş, the leader of the imprisoned Kurdish political movement, said: **'It's not the state that killed Tahir, it's statelessness'**

**Comment by ghost** [comment]
@Crissov We need this. Please do not abandon us.

**Comment by roj1512** [comment]
@L8X He doesn't have anything to do with it. He is just reporting.

**Comment by Lindafahmi** [comment]
Roj ***@***.***> schrieb am So. 29. Jan. 2023 um 11:40:

**Comment by KurdishBoy93** [comment]
We need to make this emoji to be accepted.

**Comment by KurdishBoy93** [comment]
We should do everything to make this Emoji to be accepted.

**Comment by sabermazoji** [comment]
I'm determined to do whatever it takes to have this emoji added.

**Comment by Crissov** [comment]
At this point, that would require forming a nation-like entity that was recognized by – ideally – the UN under international law.

**Comment by Shvan-ali** [comment]
> At this point, that would require forming a nation-like entity that was recognized by – ideally – the UN under international law.

How about a campaign where a large number of people use the Tajikistan flag emoji for a month? Could this help raise awareness and support for the flag?

**Comment by Crissov** [comment]
Unicode is aware. Kurdistan simply does not meet the criteria they require.

**Comment by Mirac35** [comment]
You can use Ghana or Senegal flag :)

**Comment by a7medpa** [comment]
> You can use Ghana or Senegal flag :)

Why grave dig this issue whilst contributing nothing? It seems that you're deliberately trying to provoke a response and agitate people in order to get attention.

**Comment by Mirac35** [comment]
> > You can use Ghana or Senegal flag :)
> 
> Why grave dig this issue whilst contributing nothing? It seems that you're deliberately trying to provoke a response and agitate people in order to get attention.

Contribute nothing? Mine was definately most logical contribute of all times in this topic.

**Comment by amad-a96** [comment]
> > > You can use Ghana or Senegal flag :)
> > 
> > Why grave dig this issue whilst contributing nothing? It seems that you're deliberately trying to provoke a response and agitate people in order to get attention.
> 
> Contribute nothing? Mine was definately most logical contribute of all times in this topic.

Most logical for you is to use Mongolia flag 🇲🇳
