### ISSUE TITLE
Coin emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#137]
There are several money emojis 💸💵💴💶💷💰, but no Coin. Medals 🏅🥇🥈🥉🎖 don’t count, but look similar if the ribbon was removed. Common denominations are 1, 2, 5, 10, 20, 50. Some issuers also have a 25 denomination, most notably for the US dollar. Before the 19th century, less systematic denominations were the norm, including vulgar fractions of the base currency like 1/3.

Related: #234 Gold

Coins, especially of the smallest denomination are sometimes considered lucky charms (e.g. like horseshoes #218).

Prior art
----------

Japanese carrier E-Mobile / eAccess had a coin emoji [![# 266 = Shift-JIS F86D](http://www001.upp.so-net.ne.jp/hdml/emoji/m/F86D.gif)](http://cgi.wap2.jp/emoji/emobile/) that (like the HIT emoji ![# 261 = F868](http://www001.upp.so-net.ne.jp/hdml/emoji/m/F868.gif)) was not considered for inclusion in Unicode for some reason. https://t.co/nW2A5zTtSr

![E-Mobile emoji](https://cloud.githubusercontent.com/assets/6200185/26667282/a39128a6-46a4-11e7-9343-d43a26df6581.jpg)
![# 261 Squared HIT, # 266 Coin](https://cloud.githubusercontent.com/assets/6200185/26667291/b0cde40a-46a4-11e7-9bfa-1aa7254a02bf.png)

Screenshot taken from an archived copy of [http://emobile.jp/service/pdf/mail_change_201109.pdf](https://web.archive.org/web/20140629065651/http://emobile.jp/service/pdf/mail_change_201109.pdf) (last page). E-Mobile (or &ldquo;EMOBILE&rdquo;)  was the cell phone brand of E-Access (or &ldquo;e&middot;Access_&rdquo;), was acquired by Softbank in 2013 and got merged in 2014 with Willcom into the Yahoo-themed Y!-Mobile brand. Its emojis are a superset of the original NTT Docomo i-mode emojis because as a data service provider they cooperated with NTT to provide voice services. (Or so I assume.)

Proposals
----------

- [L2/17-229](http://www.unicode.org/L2/L2017/17229-coin-emoji.pdf) (apparently rejected at UTC#152)

**Comment by q2apro** [comment]
I wonder why there is already a bitcoin emoji but still no coin symbol!

**Comment by Crissov** [comment]
🪙 Coin

**Comment by q2apro** [comment]
![image](https://user-images.githubusercontent.com/6764548/107857136-37989280-6e35-11eb-804f-39b79056b34e.png)

**Comment by Crissov** [comment]
You’d need to update your system. 

https://emojipedia.org/coin
