### ISSUE TITLE
Sewing emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#165]
Sewing, Sewing Machine or Needle and Thread for making and fixing clothing, Tailoring.

**Comment by Crissov** [comment]
https://github.com/amandabee/Sewing-Emoji

**Comment by amandabee** [comment]
If anyone wants to help, this is my current to-do list: 

- Can you suggest alternate uses for a spool, safety pin or ball of yarn? 

- My list of alternate uses for a needle and thread include sutures, mending, tailoring, alterations, embroidery, sail making. Help me think of others? Especially unusual ones? 

- Do you know anything about the history of knitting or spools?

**Comment by Crissov** [comment]
The candidate emojis for Unicode 11 include a Spool of Thread and a Ball of Yarn emoji as U+1F9F5 and U+1F9F6, respectively.
http://www.unicode.org/L2/L2017/17284-emoji-recs.pdf
