### ISSUE TITLE
❤️🖤💚 Pan-African Flag emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#203]
People are using flag emojis to show their home, origin or heritage. This sometimes matches current nation states and their flags, but often it does not. American descendants of African slaves, for instance, often can’t really specify a country of origin for some of their ancestors, but would be fine with using the continent instead. There is a [Pan-African flag](https://en.wikipedia.org/wiki/Pan-African_flag) designed and adopted by UNIA, showing red, black and green horizontal stripes, but it is not the flag of any administrative entity. The current flag of Libya 🇱🇾 comes closest, but has a white Islamic Crescent Moon and Star in its center.

[![UNIA flag](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_the_UNIA.svg/320px-Flag_of_the_UNIA.svg.png)](https://commons.wikimedia.org/wiki/File:Flag_of_the_UNIA.svg)

Possible solutions
------------------

ISO 3166/MA won’t assign the codes `AP` and `OA`,  because they are used by WIPO Standard ST.3 for the _African Regional Industrial Property Organization_ and the _African Intellectual Property Organization_, respectively. Font vendors therefore could use the respective RIS letter sequences, 🇦🇵 U+1F1E6-1F1F5 and 🇴🇦 U+1F1F4-1F1E6, to access a Pan-African Flag emoji glyph, but that has no precedence.

[CLDR](http://unicode.org/repos/cldr/tags/latest/common/validity/region.xml) uses the numeric ISO 3166-1 macroregion code `002` inherited from [UN M.49](http://unstats.un.org/unsd/methods/m49/m49regin.htm) for _Africa_, which is not supported by Unicode (neither by Regional Indicator Symbols nor by [UTR#51 Tag sequences](http://www.unicode.org/reports/tr51/proposed.html#def_emoji_tag_sequence)). Extending [UTR#51](http://www.unicode.org/reports/tr51/proposed.html#valid-emoji-tag-sequences) to support numeric codes would be straightforward, however: <tt>🏳<u>002✦</u></tt> &#x1F3F3;&#xFE0F;&#xE0030;&#xE0030;&#xE0032;&#xE007f; U+1F3F3-FE0F-E0030-E0030-E0032-E007F or <tt>🏴<u>002✦</u></tt> &#x1F3F4;&#xE0030;&#xE0030;&#xE0032;&#xE007f; U+1F3F4-E0030-E0030-E0032-E007F. This should probably be the **preferred solution**!

~~~ xml
<id type="region" idStatus="macroregion">
<!--  34 items  -->
001~3 005 009 011 013~5 017~9 021 029 030 034~5 039 053~4 057 061 142~3 145 150~1 154~5 419 EU EZ QO UN
</id>
~~~

> - `002` Africa
>      - `014` Eastern Africa
>      - `017` Middle Africa
>      - `015` Northern Africa
>      - `018` Southern Africa
>      - `011` Western Africa

CLDR also previously used the private-use code `QU` for the European Union, before this macroregion got assigned the official code `EU`. `XA` 🇽🇦, for instance, could be used for “Africa” in theory, but [Unicode is unlikely to adopt private-use codes](http://unicode.org/cldr/trac/ticket/9972) just for emoji flags. (`QA` is already used for Qatar, private use starts with `QM`.) The [African Union (AU)](https://en.wikipedia.org/wiki/African_Union) has no ISO alpha-2 code – `AU` is already used for Australia 🇦🇺 – and actually has a different [official flag](https://en.wikipedia.org/wiki/Flag_of_the_African_Union), which shows yellow stars and the continent silhouette lit by a white sun on a green background.

[NATO](https://en.wikipedia.org/wiki/List_of_NATO_country_codes) uses `FF` and `FFF` to encode the continent of _Africa_ in STANAG 1059, but ISO does not guarantee [compatibility](https://gist.github.com/Crissov/cc8880a922bc579b81c576e7f5c418ce) with this standard. (Alpha-3 codes are currently compatible, alpha-2 ones are only occasionally equal.) The respective RIS sequence 🇫🇫 U+1F1EB-1F1EB should therefore not be used.

In the meantime, people could agree to use a color-coded sequence like ❤️&zwj;🖤&zwj;💚 U+2764[-FE0F][+200D]+1F5A4[+200D]+1F49A.

**Comment by Crissov** [comment]
Mockups
----------

Emojitwo: ![Pan-African flag](https://cloud.githubusercontent.com/assets/6200185/26754648/d60861ba-487e-11e7-8d71-edfc75dd4799.png) ![Panafrican flag](https://cloud.githubusercontent.com/assets/6200185/26754649/d60966d2-487e-11e7-8837-55ba05ead76e.png)

**Comment by bcmayes** [comment]
I am new to this. I'd like to see the UNIA/Pan-African/RBG flag as an emoji. What do I need to do to get involved?

**Comment by Crissov** [comment]
If you want to register an Emoji ZWJ Sequence, like the one with three hearts, you should follow http://unicode.org/emoji/selection.html#new_sequences You should also convince at least one vendor to support you. I don't think Emojitwo counts yet.

If you think Emoji Tag Sequences should be extended to support numbers for macroregions in flag sequences, you would probably rather write a free-form proposal to change/amend UTS#51.

**Comment by clt449** [comment]
I'm happy to hear someone has thought about this. The 100th anniversary of the flag is this month.

**Comment by KwameTaylor** [comment]
I'm so happy to happen upon this as well! It's unacceptable that we've been left out of emojis!

**Comment by JFKII** [comment]
I'm going to work on this later in the month. This should be done.

**Comment by Crissov** [comment]
- 🔴⚫🟢
- 🟥⬛🟩

**Comment by Tharness60** [comment]
Any new details on getting a flag in IOS

**Comment by mhotep** [comment]
> I'm happy to hear someone has thought about this. The 100th anniversary of the flag is this month.

August 13th is the 100th anniversary of the flag.

**Comment by Tharness60** [comment]
I’m learning on how to make it happen I have plenty of friends that will use the emoji yes the time is coming soon rip Marcus Garvey

**Comment by tolumusic** [comment]
Flagging (😎) this to keep the thread alive.
A further ≈25,000 people would like this to happen too over at [change.org](https://www.change.org/p/apple-we-want-a-pan-african-african-american-flag-emoji?redirect_reason=missing_promotion_data) 
Any updates from Unicode Consortium lately?

**Comment by Tharness60** [comment]
??? What happen

**Comment by Crissov** [comment]
I closed all issues for flag emojis, because Unicode won’t outside them anymore.

**Comment by Tharness60** [comment]
So it’s just a lost cause ??

**Comment by Crissov** [comment]
For now it is, yes.

**Comment by JFKII** [comment]
That's fucked up!

JFK
@JamesFeltonKeith

**Comment by patcon** [comment]
Agreed. I've started keeping a rough account of all the ways the Unicode consortium and other web standards bodies has demonstrated themselves not to be committed to supporting causes of marginalized groups, and it's pretty disappointing what they chose not to drive forward on 😞

**Comment by JFKII** [comment]
That account might be interesting to a few newspapers on Juneteenth (June
19th) this year. Let me know if you need help publishing it.


Pronouns: He/Her/Heru𓅊

www.JamesFeltonKeith.com


IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

**Comment by Crissov** [comment]
## Update

Unlike all other flag proposals, this one might actually have a small chance after all, because Unicode might still introduce a way to add flags for continents like Africa. 

<https://www.unicode.org/L2/L2022/22094r-reg-emoji-struct.pdf>

**Comment by evecodex** [comment]
Unicode is opening up proposals again in April 2026 https://unicode.org/emoji/proposals.html @Crissov

**Comment by evecodesx** [comment]
@Crissov @JFKII Unicode is opening up proposals again in April 2026 https://unicode.org/emoji/proposals.html

**Comment by JFKII** [comment]
How do we want to coordinate this?

I'm adding Bryan to this thread.

JFK
@JamesFeltonKeith
