### ISSUE TITLE
❤⭕💙 Sami Flag emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#205]
A Flag for the Sami people or Lapland exists, but since the area is divided among several countries, the most appropriate Unicode representation is not obvious. 

![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Sami_flag_large.png/320px-Sami_flag_large.png)

For Finland, `FI-10` would be the ISO 3166-2 code which can be encoded as an Emoji Flag Tag Sequence according to [UTR#51.10+](http://unicode.org/reports/tr51/proposed.html#flag-emoji-tag-sequences).

As an alternative, an Emoji ZWJ Sequence could be used, e.g. ❤&zwj;💚&zwj;💛&zwj;💙 or ❤&zwj;⭕&zwj;💙.

**Comment by Crissov** [comment]
The Emoji Subcommittee at the Unicode consortium has recently added an exclusion criterion for [Region Flags without Code](https://www.unicode.org/emoji/proposals.html#Region_Flags_Without_Code).

**Comment by kamerat** [comment]
I have little insight in unicode.org and its processes, but I find it confusing on behalf of the Sami flag.
[This list](http://www.unicode.org/emoji/emoji-requests.html) says both (A) and (B) are declined, but [this list](https://docs.google.com/spreadsheets/d/e/2PACX-1vTChOh3prKvohxG_MLA1PJHEdB65IpwCdQQ2WHxbwKhAWtKYc5Z_gk5fGK0Y0mZxfijjVzoSN5L2KEF/pubhtml) says only (B) is declined but (A) is added to a larger set.

Do you know if the flag is declined or if it is going to be added?

**Comment by Crissov** [comment]
The latest policy changes suggest that Unicode won't recommend any new flag emojis for the time being. However, emoji fonts may include glyphs for regional flags like this which have established ISO 3166-2 codes.

**Comment by rogue-agent** [comment]
What is the progress of accession? I'm also wanting Karelia to be also added.

**Comment by rogue-agent** [comment]
https://toolbox.finland.fi/finland-images/the-sami/ Finland has also introduced it.
