### ISSUE TITLE
Bisexual  ‍🏳⚥, Transgender  ‍🏳⚧, Intersex  ‍🏳☿ Flag emojis

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#206]
Ever since the Rainbow Flag emoji 🏳️‍🌈 – which stands variably for the Peace Movement, Gay Pride, the LGBTQ… community etc. – has been documented by Unicode, [other sexuality flags](https://commons.wikimedia.org/wiki/Category:LGBT_flags) or [symbols](https://commons.wikimedia.org/wiki/Sexual_identity_symbols) have been requested as well. This includes most prominently [Bisexuality](https://commons.wikimedia.org/wiki/Bisexualism_symbols) and [Transsexuality / Transgenderism](http://commons.wikimedia.org/wiki/Category:Transgender_symbols). Alas, there are often multiple flag proposals for these (which is of no concern to Unicode itself, but to possible implementers who make up that consortium).

The most appropriate Unicode representation for these would probably be a ZWJ sequence as well. They could be using the existing symbols ⚥ U+26A5 Male and Female Sign, ⚤ U+26A4 Interlocked Female and Male Sign, ⚦ U+26A6 Male with Stroke Sign or ⚧ U+26A7 Male with Stroke and Male and Female Sign.  ‍🏳&zwj;⚥&#xFE0F; ‍ ‍🏳&zwj;⚤&#xFE0F; ‍ ‍🏳&zwj;⚧&#xFE0F; ‍ ‍🏳&zwj;⚧&#xFE0F; U+1F3F3[-FE0F]-200D-26A4/5/6/7[-FE0F]. The Mercury symbol ☿ U+263F has also been used to represent Transgenders or Non-Binaries (incl. Intersex), hence  ‍🏳&zwj;☿&#xFE0F; U+1F3F3[-FE0F]-200D-263F[-FE0F].

![](https://img1.etsystatic.com/136/0/7761993/il_fullxfull.901511031_k5av.jpg)

**Comment by Crissov** [comment]
Also see #329 for more color options.

**Comment by Crissov** [comment]
There apparently have been proposals for flags like these, which have not been published by Unicode (yet), e.g. https://www.tedeytan.com/2017/06/30/22476

**Comment by Crissov** [comment]
Mockups
----------

Emojitwo: 

![androgynous](https://user-images.githubusercontent.com/6200185/29007037-43cac02c-7afb-11e7-9a23-6db5a3d80ce5.png) ![androphilia](https://user-images.githubusercontent.com/6200185/29007038-43cce104-7afb-11e7-869f-03174d02be3d.png) ![aromantic](https://user-images.githubusercontent.com/6200185/29007039-43cdc236-7afb-11e7-9ddc-0aa7e06e0b0f.png) ![asexual](https://user-images.githubusercontent.com/6200185/29007041-43dff17c-7afb-11e7-93b3-b92ef903a9b7.png) ![autosexual](https://user-images.githubusercontent.com/6200185/29007043-43e5708e-7afb-11e7-8ae5-5215feb91f8a.png) ![bear](https://user-images.githubusercontent.com/6200185/29007044-43e58506-7afb-11e7-902f-fcabd61c7a2b.png) ![bisexual](https://user-images.githubusercontent.com/6200185/29007045-43e5b54e-7afb-11e7-80cc-8a7b3654e019.png) ![demiromantic](https://user-images.githubusercontent.com/6200185/29007042-43e4ff82-7afb-11e7-9c48-700a77493c5d.png) ![gay](https://user-images.githubusercontent.com/6200185/29007046-43e6c0e2-7afb-11e7-84ff-07ea149851b0.png) ![gender binary](https://user-images.githubusercontent.com/6200185/29007047-43f6d07c-7afb-11e7-9ff1-556042a4b365.png) ![gender non-binary](https://user-images.githubusercontent.com/6200185/29007048-43ff2664-7afb-11e7-9960-e83a593e0ef7.png) ![genderqueer](https://user-images.githubusercontent.com/6200185/29007049-43ff8fdc-7afb-11e7-8808-86927ee92917.png) ![greyromantic](https://user-images.githubusercontent.com/6200185/29007050-44020f6e-7afb-11e7-898e-b5bb6504ba4d.png) ![gynephilia](https://user-images.githubusercontent.com/6200185/29007051-44023aa2-7afb-11e7-9cab-37332f77e90a.png) ![hermaphrodite](https://user-images.githubusercontent.com/6200185/29007052-44030bee-7afb-11e7-8458-2058e487d313.png) ![intersexual](https://user-images.githubusercontent.com/6200185/29007053-440cce04-7afb-11e7-80bf-dab0dabdc099.png) ![lipstick lesbian](https://user-images.githubusercontent.com/6200185/29007054-4416bfc2-7afb-11e7-9637-9153bcadb739.png) ![lithromantic](https://user-images.githubusercontent.com/6200185/29007031-43b394d8-7afb-11e7-9324-f66ab9d2e808.png) ![neutrois](https://user-images.githubusercontent.com/6200185/29007032-43b3c714-7afb-11e7-9c81-48fcb8b6e05b.png) ![pansexual](https://user-images.githubusercontent.com/6200185/29007033-43b44234-7afb-11e7-8fee-1bae923128a1.png) ![polyamorous](https://user-images.githubusercontent.com/6200185/29007030-43b326c4-7afb-11e7-8196-05db03fbf04b.png) ![polysexual](https://user-images.githubusercontent.com/6200185/29007034-43b4d528-7afb-11e7-817a-b75b8570df55.png) ![skoliosexual](https://user-images.githubusercontent.com/6200185/29007029-43b2f398-7afb-11e7-8450-f8ac28f03f4b.png) ![straight ally](https://user-images.githubusercontent.com/6200185/29007035-43c7f5b8-7afb-11e7-8634-564db961dcbb.png) ![transexual](https://user-images.githubusercontent.com/6200185/29007036-43ca7888-7afb-11e7-8e71-0c2d47072ab8.png) ![transgender](https://user-images.githubusercontent.com/6200185/29007040-43d116c0-7afb-11e7-8ecc-64e4344a2a72.png)

**Comment by pauldhunt** [comment]
in my own work with Unicode, i have advocated for ☿ to be used for ‘gender inclusive’ representation (more palatable to conservative types than genderqueer). i haven’t been following the ESC discussions very closely recently, sorry for dropping the ball on this.

**Comment by Hasimir** [comment]
Any particular reason you're not including the [intersex flag](http://oii.org.au/22773/an-intersex-flag/), while retaining the references to hermaphrodites (usually considered offensive) and intersexual (which is inaccurate, intersexuality relates to biological selection, ref. Darwin)?

**Comment by Crissov** [comment]
For some of these, there does not seem to be _the_ one and only flag, but several proposed designs used by different groups to different degrees. This is a problem for getting any of them approved, because since there is no central authority defining them (like there is for each national flag) vendors would probably only want to include uncontroversial ones. That means both the flag design and the symbol used in the sequence, perhaps also the English designation, should be well known and generally agreed upon. Above, I relied on sources that provided a wide overview, but obviously not a complete one.

**Comment by Hasimir** [comment]
Ah, yeah, that's a good reason short of adding multiple flags.  I only recall two, but one of them's a stripey thing with similar colouring to the trans flag and it's easy to confuse them (which is somewhat ironic, but not really desirable) and the other one is the purple circle on the gold background that I linked to.

**Comment by alysdexia** [comment]
The interlocked one means mates, like the other doubled figures ⚣⚢.

**Comment by bbappserver** [comment]
> The rainbow flag, commonly known as the gay pride flag or LGBT pride flag, is a symbol of lesbian, gay, bisexual and transgender (LGBT) pride and LGBT social movements. Other older uses of rainbow flags include a symbol of peace. The colors reflect the **diversity** of the LGBT community,

https://en.wikipedia.org/wiki/Rainbow_flag_(LGBT_movement)

The **rainbow pride flag is more than sufficient to represent diverse sexualities** which are a a definitely fixed construct. Though the rainbow flag already represents all different kinds of sexual orientations other groups however wish to identify with special flags for various political reasons- but **I believe it is unnecessary and burdensome to fill up code-points with symbols which may only be temporarily in vogue, and which may hold no meaning in 30 years**.

Sex research is still in its infancy and not enough research has yet to establish firm categories for common human sexual behaviours.  
Recent studies have developed a variety of novel classifications, but there is yet to be a strong consensus, especially within human society as a whole.  It would be prudent to revisit the issue 30 years down the line to check and see if the same  classifications and symbologies are used.

Further, sexualities may be to some degree arbitrarily assigned labels which may then be permuted.  Sexuality may also be recursively subdivided arbitrarily into categories.  By inserting flags for specific sexualities into the standard, you are necessarily excluding the "less important" sexualities.  This opens the floor for yet more arbitrary labels to demand inclusion, in a task which may never be completed.  By simply adoption the rainbow flag to mean sexual diversity, you avoid this issue entirely.

**Comment by jonfortescue** [comment]
Adding even some of these flags would absolutely fill me with joy. I acknowledge fully that these categories are fluid and ever changing, but this is true of language and writing itself as well. As expression, language, and culture changes, so too should the standards we use to write them. I agree with @bbappserver that it will be useful to revisit this thirty years down the line to see if the same categories are still relevant and used, but I see no reason why we can't let people express the categories (many of which I might add do have quite a long history of usage) starting now.

**Comment by Crissov** [comment]
Emoji 13.0 in 2020 added the [🏳️‍⚧️ Transgender Flag](https://emojipedia.org/transgender-flag/).

**Comment by Weirdo1312** [comment]
is lesbian flag planned?
![image](https://user-images.githubusercontent.com/37030489/131247586-8e79ada7-edbf-4713-a7a1-9128793b1ead.png)
