### ISSUE TITLE
Hot emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#217]
There is no emoticon to indicate Sweating from Heat or Feeling Hot, Warm, Burning or Melting, but a Fire emoji 🔥.  There’s also none for the opposite feeling. #216 

## Petitions

- [Emoji Request ![Hot](https://www.emojirequest.com/images/HotEmoji.jpg)](https://www.emojirequest.com/r/HotEmoji)
- [Emoji Request ![Overheat](https://www.emojirequest.com/images/OverheatedEmoji.jpg)](https://www.emojirequest.com/r/OverheatedEmoji)
- [Emoji Request ![Sweating](https://www.emojirequest.com/images/SweatingEmoji.jpg)](https://www.emojirequest.com/r/SweatingEmoji)

**Comment by Crissov** [comment]
The candidate emojis for Unicode 11 include a Hot emoji as U+1F975.
http://www.unicode.org/L2/L2017/17284-emoji-recs.pdf

**Comment by sdaitzman** [comment]
🥵
