### ISSUE TITLE
Donkey emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#232]
There are several Horse emojis 🐴🐎🏇🎠, including a Unicorn 🦄 and a Zebra 🦓  (in Unicode 10), but no **Donkey, Ass or Mule**. They may look very similar, but have very different metaphorical and symbolic meanings. Donkeys are considered stubborn and stupid, whereas horses are considered diligent and elegant. Unlike horses, donkeys and halfbreeds are mostly gray to black, smaller and have only a very short mane.

In the US, the two major political parties are frequently represented by an elephant 🐘 and a donkey.

**Comment by spixi** [comment]
I already proposed this.

The official answer of the committee:

>Hello again,
>
>The committee is still discussing this with two sets of considerations 
>in mind.
>
>* We are already considering a larger set of animals, and trying to 
>determine the priority if this vs the others,
>
>* We are also trying to determine whether it reasonable to handle 
>certain animals with closely related appearances using variation tag 
>sequences (e.g. donkey as variation of horse)
>
>The proposal is being held pending outcome of those discussions.
>
>Regards,

**Comment by Crissov** [comment]
Yeah, the Tag sequence idea is just stupid, at least for different species. The "we're preparing a larger collective proposal" is mostly a bullshitty way of saying "shelved indefinitely" if you look at the animal proposals published in July 2017: why would they not be part of the collective proposal?

**Comment by spixi** [comment]
[This proposal has been rejected from the UTC.](https://github.com/Crissov/unicode-proposals/files/1799306/proposal.pdf)

**Comment by Crissov** [comment]
As far as I know, the proposal is being (or could be) reconsidered with a stronger focus on a last carrying glyph of a donkey, ass or mule.

**Comment by spixi** [comment]
@Crissov: Yes, I actually intended to have a common character for donkeys, mules and hinnies with a stronger focus on the pack animal character. I just do not understand why zebra and unicorn have been added, but the donkey has not.

**Comment by Crissov** [comment]
The reasonings for rejections and approvals of emoji proposals are often hard to understand and are never made public officially. For Baseball and Softball it is sufficient to only differ by color, but for Horse and Donkey this and the various other differences in appearance are not sufficient.

**Comment by spixi** [comment]
That is why I purposely included a comparsion picture in my proposal. A zebra has actually more in common with a horse than a donkey. Besides of their stripe pattern, their wild behavior , the stiff mane and the less hairy tail, there are only minor differences like shorter legs, smaller nostrils, larger eyes and eyelashes. The only difference between a unicorn and a horse is the horn (and they are often depicted white with pastel- or rainbow-colored mane and tail). Donkeys, however, have a much more disctinct appearance.

**Comment by samastur** [comment]
Any recent news about donkey emoji proposals? I cannot find information if any proposal is still open.

**Comment by spixi** [comment]
If it were for some participants, we will get tons of QID emoji sequences, which will be a total mess IMHO. This one would be a donkey: Q3537778.

**Comment by ghost** [comment]
This rejection is such a blow to Democrats in the US. I would love to see this added. Also, donkeys are [way more adorable](https://twitter.com/JeremiahLee/status/1324725435398197249) than horses.

**Comment by kingdonb** [comment]
I had to use Horse emoji for Donkey on a Waffle, my Android phone passed it off as Donkey but we all know it was a horse on a pancake. This is an actual travesty, we need donkeys in Unicode sooner than later.

**Comment by Jiehong** [comment]
Another characteristic is the length of the ears (and potentially hair length, depending on the species).

Instead of horse, perhaps "equidae" would have been better, and more generic.

As a matter of fact, why are animals included like that? There are thousands of species of animals and plants (tulip, rose, sunflowers are part of the emojis, but not Lilly or orchid for some reasons).

**Comment by spixi** [comment]
> 
> 
> Another characteristic is the length of the ears (and potentially hair length, depending on the species).
> 
> Instead of horse, perhaps "equidae" would have been better, and more generic.
> 
> As a matter of fact, why are animals included like that? There are thousands of species of animals and plants (tulip, rose, sunflowers are part of the emojis, but not Lilly or orchid for some reasons).

I remember I had a plant guide (Kosmos Tier- und Pflanzenführer) as a kid, which had those characters for the thumb index which was based on the shape of the flower. The sunflower was used for aster-like composite flowers, for example. In that case tulip and lily share the same shape. Your proposed orchid character can be used for flowers with only one axis of symmetry. Maybe one emoji per flower shape would be fine.

**Comment by Jiehong** [comment]
> Maybe one emoji per flower shape would be fine.

I wouldn't even personally mind having 1 emoji per flower family, as you say for asteraceae or liliaceae, etc, because you can argue that the number and shape of petals, stamens and pistil make then totally different plants… but it's a slippery slope.

Where does one _arbitrarily_ stop? Unicode has a finite size.

So not having a donkey but having 3 horses seems like an injustice (and a prejudice to donkeys? I mean, I have one so I _know_ those are prejudices :D ).

I think a clear and transparent decision criteria for emoji inclusion is the real solution here.

**Comment by spixi** [comment]
> 3 horses
There are in fact 11 horse emojis 🐴🐎🦄🦓🎠🏇🏇🏻🏇🏼🏇🏽🏇🏾🏇🏿

Regarding flowers, I prefer the flower shape over the plant family, because some families have very variable flowers.

**Comment by Crissov** [comment]
Candidate for 2022 Emoji 15.0

https://emojipedia.org/donkey/
