### ISSUE TITLE
Axe emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#245]
There are some tool emojis, but no Axe or Hatchet emoji, which are among the oldest tools known to humankind. They are still used for chopping trees for wood and animals for meat.

The Labrys double-axe is also used as a symbol for lesbianism. #206 

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Labrys-symbol.svg/99px-Labrys-symbol.svg.png)
  
Proposals
-----------

- [L2/18-002](http://www.unicode.org/L2/L2018/18002-axe-emoji.pdf "Axe Emoji Submission by Brandom Gamm (2017-11-20)")

**Comment by vvasuki** [comment]
It is a symbol of a sage of a major Indian clan as well.

**Comment by Crissov** [comment]
[Candidate for Emoji 12.0 (2019)](http://emojipedia.org/axe)
