### ISSUE TITLE
💙‍☸️‍💚 Romani Flag emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#274]
There are several [stateless “nations”](https://commons.wikimedia.org/wiki/Flags_of_stateless_nations). Some peoples do not have a country (and therefore flag emoji) because any area inhabited primarily by them is part of another country or divided among several countries (e.g. Kurdish #117 and Sami #205), but the Roma are spread in a diaspora across many countries without any larger region having them in a majority. Also, traditionally, many of them have been moving around a lot. Their [Romani Flag](https://en.wikipedia.org/wiki/Flag_of_the_Romani_people), also known as “Gypsy Flag”, shows a blue and a green horizontal bar with either a stylized red wheel (💙‍💚‍☸️ / 💙‍☸️‍💚 as on the Indian flag 🇮🇳) or a horse head (💙‍💚‍🐴 / 💙‍🐴‍💚) on top.

![Western Romani flag with _chakra_ wheel](https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Flag_of_the_Romani_people.svg/300px-Flag_of_the_Romani_people.svg.png)

There is no applicable code in any part of ISO 3166, but [ISO 639 language codes](http://www.iso.org/iso/language_codes) include `ROM` for the Romany language.

**Comment by Crissov** [comment]
Mockups
----------

Emojitwo: ![Romani flag](https://cloud.githubusercontent.com/assets/6200185/26754867/f4a150ce-4882-11e7-9066-db8a286ad6ba.png)

**Comment by nasko86** [comment]
Hello @Crissov  and all, 
I am trying to find the Roma flag emoji and all I find is this post. 
Trying to copy/paste it and place it on a facebook status but does not really function. Am I doing something wrong?>
Please help me to find the Romani flag emoji/emoticon
Thank you :)
Atanas

**Comment by Crissov** [comment]
The last paragraph in the initial comment means that there is currently no Romani Flag emoji and there currently also is no agreed-upon possibility to encode it at all. Work-arounds are custom sequences like 💙‍☸️‍💚 and, well, images where available. I'm more verbose in other flag-related issues.

**Comment by nasko86** [comment]
Thank you for the quick reply @Crissov! I am working for Roma civil society for 15 years now, as I understand there is "no-agreed-upon possibility to encode it all"
Who decides on this? Is there an entity we need to agree with, petition, e-mail?
I will be happy if you provide me with little info around the procedure.
Thank you!
Atanas

**Comment by Crissov** [comment]
This repository is about possible future proposals to Unicode, mostly emojis. They are aware of the general issue, but have yet to come up with a solution.

<https://www.unicode.org/emoji/proposals.html#Flags>

[Emojipedia blog article](https://blog.emojipedia.org/emoji-flags-explained/)

**Comment by Crissov** [comment]
- 💙❤💚
- 🔵🔴🟢
- 🟦🟥🟩
- 🟦🔴🟩
- 🔵🐴🟢
- 🟦🐴🟩
- 🔵☸🟢
- 🟦☸🟩
- also see #189

**Comment by stoph88** [comment]
gross
