### ISSUE TITLE
Tearing-up Face emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#374]
Wechat/QQ #359 have a _Tearing up_ emoticon with dewy/bleary/watery eyes for `:'|` that has no good equivalent among existing Unicode emojis, despite :cry: and :sob: or :disappointed: and :disappointed_relieved:.

![tearing up](https://rawgit.com/qiuyinghua/wechat-emoticons/master/images/tearing_up.png)

Related: #224 Sobbing Faces

Standard References
-------------------

- [Unicode Technical Standard 51 “Unicode Emoji”](http://unicode.org/reports/tr51/) ([beta](http://unicode.org/reports/tr51/proposed.html))
- [How to propose emojis to Unicode](http://unicode.org/emoji/selection.html)
- [Unicode document submission form](http://www.unicode.org/reporting.html)

**Comment by Crissov** [comment]
The candidate emojis for Unicode 11 include a Face with Puppy Eyes emoji as U+1F97A &#x1f97a;, also known as _pleading face_, _begging face_ or _face with puppy eyes_, cf. [Emojipedia](https://emojipedia.org/face-with-pleading-eyes/).
http://www.unicode.org/L2/L2017/17284-emoji-recs.pdf

The closest emoticon Emoji Request offers to vote on, is called _Face with Puppy Eyes_:

[![Puppy Eyes](https://www.emojirequest.com/images-main/PuppyEyesEmoji.png)](https://www.emojirequest.com/r/PuppyEyesEmoji)

Viber #403 has a similar but happier _Teary_ emoticon:

![Teary](https://raw.githubusercontent.com/Crissov/original-emoji/master/viber/png/teary.png)

**Comment by Mistero5050** [comment]
I made it! 😁😁
@crissov

**Comment by Crissov** [comment]
2021 Emoji 14.0

https://emojipedia.org/face-holding-back-tears/
