### ISSUE TITLE
Reminder: Emojis for every planet in Solar System

### ISSUE THREAD

**Issue by may-son** [Crissov/unicode-proposals#426]
[Proposal from 2017](http://www.unicode.org/L2/L2017/17100-planet-emoji-seq.pdf)

It's 2021, Starship will go to Mars soon, but people can't communicate about it with Emoji... only "Ringed Planet"🪐, really?
You have Emoji that nobody uses like 📇 , yet for Mars you don't have. But it's better to add Emojis for all planets in one update.

If it's already planned, please tell me when it will be released?

**Comment by runarberg** [comment]
Could this be achieved as a zero width joiner (U+200D) sequence of the planet’s symbol (e.g. ♂ U+2642 for Mars, or ♆ U+2646 for Neptune) and the ringed planet (🪐 U+1FA90; or some more generic heavenly body symbol like a comet [☄ U+2604] or a star [⭐ U+2B50])?

**Comment by Crissov** [comment]
originally was here: #327 and still here: #120
