### ISSUE TITLE
Waffle emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#43]
Belgian and other waffles have an iconic pattern. They come in various shapes from square, over round to heart-like. It’s also a frequent request on Twitter. Related, but clearly different: [🥞](http://emojipedia.org/pancakes/)

## Petitions

- [change.org ![](https://assets.change.org/photos/7/gd/sl/iHGDslXhRQiYAiZ-800x450-noPad.jpg?1437713045)](https://www.change.org/p/apple-add-a-waffle-emoji)
- [change.org](https://www.change.org/p/waffle-emoji-help-us-create-a-waffle-emoji-b3a4aef9-9508-4562-954b-98135c404320)

**Comment by alysdexia** [comment]
"It would take so much longer to type 'waffles' than just simply click the waffle emoji."  No, you hav to find the emoji first.

**Comment by Crissov** [comment]
[Waffle](https://emojipedia.org/waffle/) is a Candidate for Emoji 12.0 (2019).
