### ISSUE TITLE
Mango emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#55]
Ripe mangos characteristically show a gradient from red through yellow to green, but are unremarkable in monochrome depictions. The flesh is also often cut in a special pattern.

## Petitions

- [change.org ![](https://assets.change.org/photos/4/zq/tw/nhZqtWRdrnZaETW-800x450-noPad.jpg?1449546893)](https://www.change.org/p/apple-create-a-mango-emoji) ❎
- [change.org ](https://www.change.org/p/jamal-geeemawl-create-a-mango-emoji)
- [Emoji Request ![](https://www.emojirequest.com/images/MangoEmoji.jpg)](http://emojirequest.com/r/MangoEmoji)

**Comment by Podgorica** [comment]
Proposed in [L2/17-203](http://www.unicode.org/L2/L2017/17203-mango-emoji.pdf) and [L2/17-211](http://www.unicode.org/L2/L2017/17211-mango-emoji.pdf).

**Comment by Crissov** [comment]
Yes, thank you @Podgorica. It seems I have missed too document some proposals released this summer. I will recheck them when the candidates for Unicode 11 are official, which should be tomorrow.

**Comment by Crissov** [comment]
The candidate emojis for Unicode 11 include a Mango emoji as U+1F96D.
http://www.unicode.org/L2/L2017/17284-emoji-recs.pdf
