### ISSUE TITLE
Skating emojis

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#65]
There are different kinds of skateboards (e.g. longboards), but as of Unicode 10.0 there is only a surfboard 🏄 and a snowboard 🏂 emoji (plus skis 🎿⛷) as well as an iceskates emoji ⛸, but no board or shoe with wheels (neither 4×1 nor 2×2).

## Petitions

- [change.org: Skateboard(er)](https://www.change.org/p/apple-unicode-emoji-a-skateboard-skateboarder-emoji-should-be-included-amongst-the-many-other-sports)
- [change.org: Roller skates](https://www.change.org/p/unicode-consortium-unicode-consortium-give-us-roller-skates)

## Proposals

- [L2/16-378 Skateboarder Emoji proposal](http://www.unicode.org/L2/L2016/16378-skateboarder-emoji.pdf)
- [L2/17-277: Consolidated sports emoji proposals](http://www.unicode.org/L2/L2017/17277-sports-emoji.pdf) includes Skateboard

**Comment by Crissov** [comment]
- [L2/16-378 Skateboarder Emoji proposal](http://www.unicode.org/L2/L2016/16378-skateboarder-emoji.pdf)

**Comment by Crissov** [comment]
The candidate emojis for Unicode 11 include a Skateboard emoji as U+1F6F9.
http://www.unicode.org/L2/L2017/17284-emoji-recs.pdf

This issue will remain open for a Rollerskate emoji.

**Comment by jcampbell05** [comment]
Whats the progress on the Rollerskate emoji ?

**Comment by Crissov** [comment]
No proposal for a Roller Skates emoji that been published and I am not aware of one being actively worked on, so feel free to write and submit your own. I would gladly offer to provide feedback and assistance.

**Comment by jcampbell05** [comment]
@Crissov yes please, where do I start ?

**Comment by Crissov** [comment]
First, read this: [How to propose emojis to Unicode](http://unicode.org/emoji/selection.html).

**Comment by Crissov** [comment]
I will keep this issue open for a Roller Skates or Inline Skates emoji.

**Comment by Crissov** [comment]
🛼 Roller Skate
