### ISSUE TITLE
Frisbee emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#69]
Frisbees are used for a number of sports and fun activities. Without a person depicted throwing one, it’s almost indistinguishable from a plate.

## Petitions

- [change.org: Frisbee](https://www.change.org/p/apple-apple-add-a-frisbee-emoji)
- [change.org: Frisbee](https://www.change.org/p/apple-please-make-a-frisbee-emoji)

## Proposals

- [L2/17-257: Flying Disc](http://www.unicode.org/L2/L2017/17257-flying-disc-emoji.pdf)
- [L2/17-277: Consolidated sports emoji proposals](http://www.unicode.org/L2/L2017/17277-sports-emoji.pdf) includes Flying Disc

**Comment by Crissov** [comment]
The candidate emojis for Unicode 11 include a Flzing Disc emoji as U+1F94F.
http://www.unicode.org/L2/L2017/17284-emoji-recs.pdf

**Comment by akvadrako** [comment]
🥏
